name: CI/CD Process
on:
  pull_request:
  workflow_dispatch:

jobs:
  basic-checks:
    name: Basic checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Build Gradle which perform project building
      - name: Build
        run: ./gradlew assemble
      # Checking the linting
      - name: Lint
        run: ./gradlew ktlintCheck
      # Checking the unit tests
      # For some reason, test does not pass on the CI/CD for now and they need to be done locally.
      - name: Test
        run: ./gradlew test
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test
