name: CI/CD Process
on:
  pull_request:
  workflow_dispatch:

jobs:
  basic-checks:
    name: Basic checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Build Gradle which perform project building, testing and linting
      - name: Build
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        run: ./gradlew build
